### ISSUE TITLE
Allow user to configure multiple local / custom models

### ISSUE THREAD

**Issue by handrew** [alexanderatallah/window.ai#14]
Would be cool to allow users to specify multiple custom endpoints (local, hosted, or otherwise) which Window apps could then call separately and potentially chain together. 

- Easiest way to do this would just be to hardcode more model slots in the `configManager`. Users could then add localhost:8000, 4545, 9001, etc.
- Less elegant way would just be to make a design decision to offload this as a user problem—i.e., have them write backend logic to route models instead. Not sure this is entirely possible unless a `model` param is also posted to the endpoint. 
- Probably the best way is to add a button which lets users add arbitrarily many endpoints, and to use local storage to store their preferences.

**Comment by alexanderatallah** [comment]
The second option actually strikes me as a bit simpler, and more consistent with the way external apis (like OpenAI) work. a `model` param could be sent to the local model (very easy to change), and an api there does the routing to the right model, avoiding the need to clutter your system's ports if you don't want to.

Will post up a starter PR to illustrate this idea, since it makes local more consistent with the rest anyway.

**Comment by handrew** [comment]
Yeah happy to take direction here, but then the worry is that the user has to do a bunch of bespoke routing themselves / the interface at the API level becomes nonstandard relative to the other endpoints Window developers might expect. 

Also happy to make changes to the local hugging face Flask API once you make it possible to get a `model` param.
